[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
casino_simple = "7eoY2tr9vaZEEjX1q64q3ovND5Erg9ZjK8CfujxDfh8p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
casino_simple = "7eoY2tr9vaZEEjX1q64q3ovND5Erg9ZjK8CfujxDfh8p"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
